//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrsPluginTests.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HICPluginTests.TestData.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PX_Count,CHI,Examination_Date,Visual_Acuity,Eye,Retinopathy,Maculopathy,Image_Num,Image_Filename,Pixel_Width,Pixel_Height,blotHaem,CWS,flameHaem,imageQuality,IRMA,laserScarsType,MA,MacBlotHaem,MaxExudates,NVD,NVE,OODARMD,OODAstHyal,OODCuppedDisc,OODDrusen,OODEpiretMemb,OODMRNF,OODPigmLesion,OODRetVeinThromb,RetDet,VB,VH
        ///2,1234567890,17/05/2016,0.2 (6/9.5),R,R0,M1,1,2_1234567890_2016-05-17_RM_1_PW1024_PH768.jpeg,1024,768,None,No,No,Nerve fibre layer not visible,No,No,No,No,No,None,None,No,No,Yes,No,No,No,No [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DRS_RETINAL_TEST_MANIFEST {
            get {
                return ResourceManager.GetString("DRS_RETINAL_TEST_MANIFEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PX_Count,CHI,Examination_Date,Visual_Acuity,Eye,Retinopathy,Maculopathy,Image_Num,Image_Filename,Pixel_Width,Pixel_Height,blotHaem,CWS,flameHaem,imageQuality,IRMA,laserScarsType,MA,MacBlotHaem,MaxExudates,NVD,NVE,OODARMD,OODAstHyal,OODCuppedDisc,OODDrusen,OODEpiretMemb,OODMRNF,OODPigmLesion,OODRetVeinThromb,RetDet,VB,VH
        ///2,1234567890,17/05/2016,0.2 (6/9.5),R,R0,M1,1,2_1234567890_2016-05-17_RM_1_PW1024_PH768.jpeg,1024,768,None,No,No,Nerve fibre layer not visible,No,No,No,No,No,None,None,No,No,Yes,No,No,No,No [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DRS_RETINAL_TEST_MANIFEST_ADDITIONAL_ENTRY {
            get {
                return ResourceManager.GetString("DRS_RETINAL_TEST_MANIFEST_ADDITIONAL_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PX_Count,CHI,Examination_Date,Visual_Acuity,Eye,Retinopathy,Maculopathy,Image_Num,Image_Filename,Pixel_Width,Pixel_Height,blotHaem,CWS,flameHaem,imageQuality,IRMA,laserScarsType,MA,MacBlotHaem,MaxExudates,NVD,NVE,OODARMD,OODAstHyal,OODCuppedDisc,OODDrusen,OODEpiretMemb,OODMRNF,OODPigmLesion,OODRetVeinThromb,RetDet,VB,VH
        ///2,1234567890,17/05/2016,0.2 (6/9.5),R,R0,M1,1,2_1234567890_2016-05-17_RM_1_PW1024_PH768.jpeg,1024,768,None,No,No,Nerve fibre layer not visible,No,No,No,No,No,None,None,No,No,Yes,No,No,No,No [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DRS_RETINAL_TEST_MANIFEST_MISSING_ENTRY {
            get {
                return ResourceManager.GetString("DRS_RETINAL_TEST_MANIFEST_MISSING_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DRS_RETINAL_TEST_PART1 {
            get {
                object obj = ResourceManager.GetObject("DRS_RETINAL_TEST_PART1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DRS_RETINAL_TEST_PART2 {
            get {
                object obj = ResourceManager.GetObject("DRS_RETINAL_TEST_PART2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DRS_RETINAL_TEST_PART3 {
            get {
                object obj = ResourceManager.GetObject("DRS_RETINAL_TEST_PART3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DRS_RETINAL_TEST_PART4 {
            get {
                object obj = ResourceManager.GetObject("DRS_RETINAL_TEST_PART4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DRS_RETINAL_TEST_PART5 {
            get {
                object obj = ResourceManager.GetObject("DRS_RETINAL_TEST_PART5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TEST_DATA_ARCHIVE {
            get {
                object obj = ResourceManager.GetObject("TEST_DATA_ARCHIVE", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
