// Copyright (c) The University of Dundee 2018-2025
// This file is part of the Research Data Management Platform (RDMP).
// RDMP is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
// RDMP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along with RDMP. If not, see <https://www.gnu.org/licenses/>.
using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyCompanyAttribute("HIC")]
[assembly: AssemblyVersionAttribute("0.0.0.0")]
[assembly: AssemblyFileVersionAttribute("0.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0.0")]
[assembly: AssemblyTitleAttribute("HIC.DataManagementPlatform")]
[assembly: AssemblyProductAttribute("HIC.DataManagementPlatform")]
[assembly: AssemblyDescriptionAttribute("HIC.DataManagementPlatform is a product of HIC - https://github.com/HicServices/RDMP.git.")]
[assembly: AssemblyTrademarkAttribute("HIC.DataManagementPlatform - HIC")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2019 HIC, - Original author or authors")]

