//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HICPluginTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestReports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestReports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HICPluginTests.TestReports", typeof(TestReports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;CombinedReportData xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;HbExtract&gt;T&lt;/HbExtract&gt;
        ///  &lt;SciStoreRecord&gt;
        ///    &lt;CHI&gt;0&lt;/CHI&gt;
        ///    &lt;LabNumber&gt;ANO&lt;/LabNumber&gt;
        ///    &lt;TestReportID&gt;0&lt;/TestReportID&gt;
        ///    &lt;ReportType&gt;&lt;/ReportType&gt;
        ///    &lt;patientid&gt;0&lt;/patientid&gt;
        ///    &lt;name&gt;&lt;/name&gt;
        ///  &lt;/SciStoreRecord&gt;
        ///  &lt;InvestigationReport&gt;
        ///    &lt;ReportData xmlns=&quot;http://www.show.scot.nhs.uk/isd/SCIStore&quot;&gt;
        ///      &lt;ReportIdentifier&gt;0&lt;/ReportIdentifi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string report_with_float_values {
            get {
                return ResourceManager.GetString("report_with_float_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;CombinedReportData xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;HbExtract&gt;T&lt;/HbExtract&gt;
        ///  &lt;SciStoreRecord&gt;
        ///    &lt;CHI&gt;0&lt;/CHI&gt;
        ///    &lt;LabNumber&gt;ANO&lt;/LabNumber&gt;
        ///    &lt;TestReportID&gt;0&lt;/TestReportID&gt;
        ///    &lt;ReportType&gt;&lt;/ReportType&gt;
        ///    &lt;patientid&gt;0&lt;/patientid&gt;
        ///    &lt;name&gt;&lt;/name&gt;
        ///  &lt;/SciStoreRecord&gt;
        ///  &lt;InvestigationReport&gt;
        ///	&lt;ReportData xmlns=&quot;http://www.show.scot.nhs.uk/isd/SCIStore&quot;&gt;
        ///      &lt;ReportIdentifier&gt;0&lt;/ReportIdentifier&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string report_with_multiple_descriptions {
            get {
                return ResourceManager.GetString("report_with_multiple_descriptions", resourceCulture);
            }
        }
    }
}
