name: Build and Bundle

# Run this workflow for pushes that don't trigger tests
on:
  push:
    branches-ignore: [ main, feature/* ]  # These branches trigger tests workflow

env:
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  # Quick build verification - runs on all pushes that don't trigger full tests
  build:
    name: Build Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          cache: true
          cache-dependency-path: Directory.Packages.props

      - name: Build
        run: dotnet build --configuration Release --verbosity minimal